database:
  host: localhost
  port: 5432
  user: postgres
  password: Fed20072
  name: BOT_TEST

bot:
  token: "7907579636:AAGPgDJsUsJPJ9IMd6jiOhbH_TT6QbqUu38"
  channelId: "@testestesttesttestes"
  botUsername: "TESTESTESTE312312bot"
  commentChatId: "987654321"
